version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.11.1
      - image: trufflesuite/ganache-cli
        command: |
          -a 50
          -e 1000000

    working_directory: ~/token

    steps:
      - checkout

      - run:
          name: Install Truffle
          command: |
            sudo npm install -E zeppelin-solidity
            sudo npm install -g truffle

      - run:
          name: Run Test
          command: |
            truffle test
